CREATE TABLE MEMBER(
    ID VARCHAR2(100) PRIMARY KEY,
    PASSWORD VARCHAR2(150) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL
);
SELECT * FROM MEMBER;

SELECT ID, PASSWORD, NAME, ADDRESS
	 	FROM MEMBER
        WHERE ID LIKE '%u%'
        OR PASSWORD LIKE '%u%'
        OR NAME LIKE '%u%'
        OR ADDRESS LIKE '%u%';