CREATE TABLE MEMBER(
    ID VARCHAR2(100) PRIMARY KEY,
    PASSWORD VARCHAR2(150) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL
);
SELECT * FROM MEMBER;

SELECT ID, PASSWORD, NAME, ADDRESS
	 	FROM MEMBER
        WHERE ID LIKE '%u%'
        OR PASSWORD LIKE '%u%'
        OR NAME LIKE '%u%'
        OR ADDRESS LIKE '%u%';
        
CREATE SEQUENCE SEQ_BOARD;
DROP TABLE BOARD;
CREATE TABLE BOARD(
    NO NUMBER,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE
);
SELECT NO, TITLE, CONTENT, WRITER, REGDATE FROM BOARD;

INSERT INTO BOARD VALUES(1, 'asd', 'asd', 'asd', '2011-12-20');

DELETE FROM BOARD WHERE NO = 1;

SELECT NO, TITLE, CONTENT, WRITER, REGDATE 
		FROM BOARD
        WHERE TITLE LIKE '%t%'
			OR CONTENT LIKE '%t%'
			OR WRITER LIKE '%t%';
UPDATE BOARD S
		TITLE = 't',
		CONTENT = 't',
		REGDATE
		WHERE WRITER = #{writer} AND NO = #{no};
SELECT * FROM BOARD ORDER BY NO DESC;
-- 힌트..!
SELECT NUM, NO, TITLE, WRITER, REGDATE, URL
FROM(
SELECT /*+ INDEX_DESC(BOARD PK_BOARD)*/ ROWNUM NUM, NO, TITLE, WRITER, REGDATE, URL FROM BOARD WHERE ROWNUM <=10
)
WHERE NUM>1;
SELECT ROWNUM NUM, NO, TITLE, CONTENT, FROM BOARD;
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER)(SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER FROM BOARD);
COMMIT;
SELECT * FROM BOARD WHERE NO = 17421;
ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY(NO);
ALTER TABLE board ADD url VARCHAR(200);
